compression:
  dct_block_size: 8
  downsampling_rate: '4:2:2'
  noise_present: false
  noise_sigma: 0
  out_location: C:\0_bilgekagan\DERSLER\7. Donem\EE 473\Project\compressed_outputs
  quantization_mode: hsv-oriented
decompression:
  downsampling_rate: '4:2:2'
  idct_block_size: 8
  interpolation_mode: bilinear
  noise_present: false
  out_location: C:\0_bilgekagan\DERSLER\7. Donem\EE 473\Project\decompressed_outputs
  quantization_mode: hsv-oriented
